# Generated by Django 5.1.5 on 2025-04-18 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techtalks', '0002_review_delete_reviewcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
